### ISSUE TITLE
課題の説明ファイルをこのリポジトリで管理するか検討

### ISSUE THREAD

**Issue by NoriyukiMatsumoto** [ncdcdev/recruit-frontend#14]
データがあっちこっちにあるのを防ぎたい

**Comment by rsogo** [comment]
ここに書いたのでクローズ。
https://github.com/ncdcdev/recruit-frontend/blob/main/%E6%8E%A1%E7%94%A8%E8%AA%B2%E9%A1%8C%E3%82%92%E5%8F%97%E3%81%91%E3%81%A6%E3%81%84%E3%81%9F%E3%81%A0%E3%81%91%E3%82%8B%E6%96%B9%E3%81%AB.md
